export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_CART_UNITS = "INCREASE_CART_UNITS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
